document.addEventListener("DOMContentLoaded", function () {
  const elements = [
    {
      symbol: "H",
      name: "Hydrogen",
      atomicNumber: 1,
      family: "nonmetals",
      atomicMass: 1.008,
      period: 1,
      group: 1,
      density: 0.08988,
      meltingPoint: -259.14,
      boilingPoint: -252.87,
      discoveryYear: 1766,
      discoveredBy: "Henry Cavendish",
      description:
        "Hydrogen is a colorless, odorless, and tasteless gas. It is the lightest element and most abundant chemical substance in the universe, primarily found in molecular form as water (H2).",
    },
    {
      symbol: "He",
      name: "Helium",
      atomicNumber: 2,
      family: "noble gases",
      atomicMass: 4.0026,
      period: 1,
      group: 18,
      density: 0.1786,
      meltingPoint: -272.2,
      boilingPoint: -268.9,
      discoveryYear: 1868,
      discoveredBy: "Pierre Janssen",
      description:
        "Helium is a colorless, odorless, and tasteless gas. It is the second lightest and second most abundant element in the universe, primarily found in stars and gas giants.",
    },
    {
      symbol: "Li",
      name: "Lithium",
      atomicNumber: 3,
      family: "alkali metals",
      atomicMass: 6.94,
      period: 2,
      group: 1,
      density: 0.534,
      meltingPoint: 180.5,
      boilingPoint: 1342,
      discoveryYear: 1817,
      discoveredBy: "Johan August Arfvedson",
      description:
        "Lithium is a soft, silvery-white alkali metal. It is the lightest metal and the least dense solid element. Lithium and its compounds have several industrial applications.",
    },
    {
      symbol: "Be",
      name: "Beryllium",
      atomicNumber: 4,
      family: "alkaline earth metals",
      atomicMass: 9.0122,
      period: 2,
      group: 2,
      density: 1.85,
      meltingPoint: 1287,
      boilingPoint: 2470,
      discoveryYear: 1798,
      discoveredBy: "Louis Nicolas Vauquelin",
      description:
        "Beryllium is a hard, grayish metal with a high melting point. It is relatively rare in the Earth's crust and has excellent thermal conductivity.",
    },
    {
      symbol: "B",
      name: "Boron",
      atomicNumber: 5,
      family: "metalloids",
      atomicMass: 10.81,
      period: 2,
      group: 13,
      density: 2.34,
      meltingPoint: 2076,
      boilingPoint: 3927,
      discoveryYear: 1808,
      discoveredBy: "Joseph Louis Gay-Lussac and Louis Jacques Thénard",
      description:
        "Boron is a metalloid with properties intermediate between those of metals and nonmetals. It is essential for plant growth and is found in various borate minerals.",
    },
    {
      symbol: "C",
      name: "Carbon",
      atomicNumber: 6,
      family: "nonmetals",
      atomicMass: 12.011,
      period: 2,
      group: 14,
      density: 2.267,
      meltingPoint: 3550,
      boilingPoint: 4827,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Carbon is a nonmetallic chemical element, with a diamond-like structure. It is essential for life on Earth and exists in various forms including graphite and diamonds.",
    },
    {
      symbol: "N",
      name: "Nitrogen",
      atomicNumber: 7,
      family: "nonmetals",
      atomicMass: 14.007,
      period: 2,
      group: 15,
      density: 0.001251,
      meltingPoint: -210.01,
      boilingPoint: -195.79,
      discoveryYear: 1772,
      discoveredBy: "Daniel Rutherford",
      description:
        "Nitrogen is a colorless, odorless, and tasteless gas. It is the most abundant element in Earth's atmosphere and is crucial for life as it is a key component of amino acids and proteins.",
    },
    {
      symbol: "O",
      name: "Oxygen",
      atomicNumber: 8,
      family: "nonmetals",
      atomicMass: 15.999,
      period: 2,
      group: 16,
      density: 0.001429,
      meltingPoint: -218.79,
      boilingPoint: -182.96,
      discoveryYear: 1774,
      discoveredBy: "Carl Wilhelm Scheele",
      description:
        "Oxygen is a colorless, odorless, and tasteless gas. It is the third most abundant element in the universe and is essential for respiration and combustion.",
    },
    {
      symbol: "F",
      name: "Fluorine",
      atomicNumber: 9,
      family: "halogens",
      atomicMass: 18.998,
      period: 2,
      group: 17,
      density: 0.001696,
      meltingPoint: -219.62,
      boilingPoint: -188.14,
      discoveryYear: 1670,
      discoveredBy: "André-Marie Ampère",
      description:
        "Fluorine is a pale yellow gas. It is the most reactive and electronegative of all elements, forming compounds with virtually all organic and inorganic substances.",
    },
    {
      symbol: "Ne",
      name: "Neon",
      atomicNumber: 10,
      family: "noble gases",
      atomicMass: 20.18,
      period: 2,
      group: 18,
      density: 0.0008999,
      meltingPoint: -248.59,
      boilingPoint: -246.08,
      discoveryYear: 1898,
      discoveredBy: "Sir William Ramsay",
      description:
        "Neon is a colorless, odorless, inert monatomic gas under standard conditions. It is the fifth most abundant element in the universe and is used in lighting.",
    },
    {
      symbol: "Na",
      name: "Sodium",
      atomicNumber: 11,
      family: "alkali metals",
      atomicMass: 22.99,
      period: 3,
      group: 1,
      density: 0.968,
      meltingPoint: 97.79,
      boilingPoint: 882.9,
      discoveryYear: 1807,
      discoveredBy: "Sir Humphry Davy",
      description:
        "Sodium is a soft, silvery-white, highly reactive metal. It is an essential element for life and is found in salts such as sodium chloride (table salt).",
    },
    {
      symbol: "Mg",
      name: "Magnesium",
      atomicNumber: 12,
      family: "alkaline earth metals",
      atomicMass: 24.305,
      period: 3,
      group: 2,
      density: 1.738,
      meltingPoint: 650,
      boilingPoint: 1090,
      discoveryYear: 1755,
      discoveredBy: "Joseph Black",
      description:
        "Magnesium is a silvery-white metal. It is the eighth most abundant element in the Earth's crust and is essential for many biological processes.",
    },
    {
      symbol: "Al",
      name: "Aluminum",
      atomicNumber: 13,
      family: "post-transition metals",
      atomicMass: 26.982,
      period: 3,
      group: 13,
      density: 2.7,
      meltingPoint: 660.32,
      boilingPoint: 2519,
      discoveryYear: 1825,
      discoveredBy: "Hans Christian Ørsted",
      description:
        "Aluminum is a silvery-white, lightweight, and nonmagnetic metal. It is the most abundant metal in the Earth's crust and is used in a wide range of applications from aircraft and packaging to construction and electrical transmission lines.",
    },
    {
      symbol: "Si",
      name: "Silicon",
      atomicNumber: 14,
      family: "metalloids",
      atomicMass: 28.085,
      period: 3,
      group: 14,
      density: 2.3296,
      meltingPoint: 1414,
      boilingPoint: 3265,
      discoveryYear: 1824,
      discoveredBy: "Jöns Jacob Berzelius",
      description:
        "Silicon is a metalloid with semiconductor properties. It is the second most abundant element in the Earth's crust after oxygen.",
    },
    {
      symbol: "P",
      name: "Phosphorus",
      atomicNumber: 15,
      family: "nonmetals",
      atomicMass: 30.974,
      period: 3,
      group: 15,
      density: 1.82,
      meltingPoint: 44.1,
      boilingPoint: 280.5,
      discoveryYear: 1669,
      discoveredBy: "Hennig Brand",
      description:
        "Phosphorus is a nonmetallic chemical element with unique applications in fertilizers, detergents, and as a component of DNA and RNA.",
    },
    {
      symbol: "S",
      name: "Sulfur",
      atomicNumber: 16,
      family: "nonmetals",
      atomicMass: 32.06,
      period: 3,
      group: 16,
      density: 2.067,
      meltingPoint: 115.21,
      boilingPoint: 444.6,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Sulfur is a multivalent nonmetal with numerous industrial uses. It is found in its elemental form as well as in sulfide and sulfate minerals.",
    },
    {
      symbol: "Cl",
      name: "Chlorine",
      atomicNumber: 17,
      family: "halogens",
      atomicMass: 35.45,
      period: 3,
      group: 17,
      density: 0.003214,
      meltingPoint: -101.5,
      boilingPoint: -34.04,
      discoveryYear: 1774,
      discoveredBy: "Carl Wilhelm Scheele",
      description:
        "Chlorine is a yellow-green gas. It is a highly reactive element and is used primarily in the production of chemicals for water purification and disinfectants.",
    },
    {
      symbol: "Ar",
      name: "Argon",
      atomicNumber: 18,
      family: "noble gases",
      atomicMass: 39.948,
      period: 3,
      group: 18,
      density: 0.0017837,
      meltingPoint: -189.34,
      boilingPoint: -185.85,
      discoveryYear: 1894,
      discoveredBy: "Sir William Ramsay and Lord Rayleigh",
      description:
        "Argon is a colorless, odorless, and inert gas. It is the third most abundant gas in the Earth's atmosphere and is used in various applications.",
    },
    {
      symbol: "K",
      name: "Potassium",
      atomicNumber: 19,
      family: "alkali metals",
      atomicMass: 39.098,
      period: 4,
      group: 1,
      density: 0.862,
      meltingPoint: 63.5,
      boilingPoint: 759,
      discoveryYear: 1807,
      discoveredBy: "Sir Humphry Davy",
      description:
        "Potassium is a soft, silvery-white metal. It is highly reactive and is stored under oil to prevent reaction with moisture in the air.",
    },
    {
      symbol: "Ca",
      name: "Calcium",
      atomicNumber: 20,
      family: "alkaline earth metals",
      atomicMass: 40.078,
      period: 4,
      group: 2,
      density: 1.54,
      meltingPoint: 842,
      boilingPoint: 1484,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Calcium is a silvery-white, alkaline earth metal. It is the fifth most abundant element by mass in the Earth's crust.",
    },
    {
      symbol: "Sc",
      name: "Scandium",
      atomicNumber: 21,
      family: "transition metals",
      atomicMass: 44.956,
      period: 4,
      group: 3,
      density: 2.99,
      meltingPoint: 1541,
      boilingPoint: 2836,
      discoveryYear: 1879,
      discoveredBy: "Lars Fredrik Nilson",
      description:
        "Scandium is a silvery-white transition metal. It is often used in aerospace and lighting industries due to its strength and resistance to corrosion.",
    },
    {
      symbol: "Ti",
      name: "Titanium",
      atomicNumber: 22,
      family: "transition metals",
      atomicMass: 47.867,
      period: 4,
      group: 4,
      density: 4.54,
      meltingPoint: 1668,
      boilingPoint: 3287,
      discoveryYear: 1791,
      discoveredBy: "William Gregor",
      description:
        "Titanium is a strong, lustrous transition metal with a silver color. It is resistant to corrosion in sea water and chlorine.",
    },
    {
      symbol: "V",
      name: "Vanadium",
      atomicNumber: 23,
      family: "transition metals",
      atomicMass: 50.942,
      period: 4,
      group: 5,
      density: 6.0,
      meltingPoint: 1910,
      boilingPoint: 3407,
      discoveryYear: 1801,
      discoveredBy: "Andrés Manuel del Río",
      description:
        "Vanadium is a hard, silvery-grey transition metal. It is used in the production of high-strength steel alloys and as a catalyst in chemical reactions.",
    },
    {
      symbol: "Cr",
      name: "Chromium",
      atomicNumber: 24,
      family: "transition metals",
      atomicMass: 51.996,
      period: 4,
      group: 6,
      density: 7.19,
      meltingPoint: 1907,
      boilingPoint: 2671,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Chromium is a hard, lustrous, steel-gray metal. It is used in stainless steels, alloy steels, and chrome plating.",
    },
    {
      symbol: "Mn",
      name: "Manganese",
      atomicNumber: 25,
      family: "transition metals",
      atomicMass: 54.938,
      period: 4,
      group: 7,
      density: 7.21,
      meltingPoint: 1246,
      boilingPoint: 2061,
      discoveryYear: 1774,
      discoveredBy: "Johan Gottlieb Gahn",
      description:
        "Manganese is a silvery-grey metal. It is an essential trace nutrient for all known living organisms and is used in steelmaking.",
    },
    {
      symbol: "Fe",
      name: "Iron",
      atomicNumber: 26,
      family: "transition metals",
      atomicMass: 55.845,
      period: 4,
      group: 8,
      density: 7.874,
      meltingPoint: 1538,
      boilingPoint: 2862,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Iron is a lustrous, ductile, and malleable metal. It is the most common element on Earth by mass, forming much of Earth's outer and inner core.",
    },

    {
      symbol: "Co",
      name: "Cobalt",
      atomicNumber: 27,
      family: "transition metals",
      atomicMass: 58.933,
      period: 4,
      group: 9,
      density: 8.9,
      meltingPoint: 1495,
      boilingPoint: 2927,
      discoveryYear: 1735,
      discoveredBy: "Georg Brandt",
      description:
        "Cobalt is a hard, lustrous, silver-gray metal. It is used in magnets, cutting tools, and alloys for jet engines and gas turbines.",
    },
    {
      symbol: "Ni",
      name: "Nickel",
      atomicNumber: 28,
      family: "transition metals",
      atomicMass: 58.693,
      period: 4,
      group: 10,
      density: 8.908,
      meltingPoint: 1455,
      boilingPoint: 2913,
      discoveryYear: 1751,
      discoveredBy: "Axel Fredrik Cronstedt",
      description:
        "Nickel is a silvery-white, hard, and ductile transition metal. It is corrosion-resistant and used in coins, stainless steel, and rechargeable batteries.",
    },
    {
      symbol: "Cu",
      name: "Copper",
      atomicNumber: 29,
      family: "transition metals",
      atomicMass: 63.546,
      period: 4,
      group: 11,
      density: 8.96,
      meltingPoint: 1084.62,
      boilingPoint: 2562,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Copper is a soft, malleable, and ductile metal. It has high thermal and electrical conductivity and is used in electrical wiring, plumbing, and architecture.",
    },
    {
      symbol: "Zn",
      name: "Zinc",
      atomicNumber: 30,
      family: "transition metals",
      atomicMass: 65.38,
      period: 4,
      group: 12,
      density: 7.14,
      meltingPoint: 419.53,
      boilingPoint: 907,
      discoveryYear: 1746,
      discoveredBy: "Andreas Sigismund Marggraf",
      description:
        "Zinc is a bluish-white, lustrous metal. It is essential for the immune system, wound healing, and is widely used in alloys, batteries, and cosmetics.",
    },
    {
      symbol: "Ga",
      name: "Gallium",
      atomicNumber: 31,
      family: "post-transition metals",
      atomicMass: 69.723,
      period: 4,
      group: 13,
      density: 5.91,
      meltingPoint: 29.76,
      boilingPoint: 2204,
      discoveryYear: 1875,
      discoveredBy: "Lecoq de Boisbaudran",
      description:
        "Gallium is a soft, silvery-blue metal. It is used in semiconductors and LEDs, and its alloys can be used in high-temperature thermometers and barometers.",
    },
    {
      symbol: "Ge",
      name: "Germanium",
      atomicNumber: 32,
      family: "metalloids",
      atomicMass: 72.63,
      period: 4,
      group: 14,
      density: 5.323,
      meltingPoint: 938.25,
      boilingPoint: 2830,
      discoveryYear: 1886,
      discoveredBy: "Clemens Winkler",
      description:
        "Germanium is a metalloid with semiconductor properties. It is used in fiber-optic systems, infrared optics, and solar cell applications.",
    },
    {
      symbol: "As",
      name: "Arsenic",
      atomicNumber: 33,
      family: "metalloids",
      atomicMass: 74.922,
      period: 4,
      group: 15,
      density: 5.776,
      meltingPoint: 817,
      boilingPoint: 613,
      discoveryYear: "Known since ancient times",
      discoveredBy: "Ancient civilizations",
      description:
        "Arsenic is a metalloid with both metallic and nonmetallic properties. It is known for its toxicity but also has applications in medicine and agriculture.",
    },
    {
      symbol: "Se",
      name: "Selenium",
      atomicNumber: 34,
      family: "nonmetals",
      atomicMass: 78.971,
      period: 4,
      group: 16,
      density: 4.809,
      meltingPoint: 220.8,
      boilingPoint: 685,
      discoveryYear: 1817,
      discoveredBy: "Jöns Jacob Berzelius",
      description:
        "Selenium is a nonmetal with properties that are intermediate between sulfur and tellurium. It is used in electronics and glassmaking.",
    },
    {
      symbol: "Br",
      name: "Bromine",
      atomicNumber: 35,
      family: "halogens",
      atomicMass: 79.904,
      period: 4,
      group: 17,
      density: 3.122,
      meltingPoint: -7.2,
      boilingPoint: 58.8,
      discoveryYear: 1826,
      discoveredBy: "Antoine Jérôme Balard",
      description:
        "Bromine is a reddish-brown liquid at room temperature. It is the only nonmetallic element that is liquid under normal conditions.",
    },
    {
      symbol: "Kr",
      name: "Krypton",
      atomicNumber: 36,
      family: "noble gases",
      atomicMass: 83.798,
      period: 4,
      group: 18,
      density: 0.003733,
      meltingPoint: -157.36,
      boilingPoint: -153.22,
      discoveryYear: 1898,
      discoveredBy: "Sir William Ramsay and Morris Travers",
      description:
        "Krypton is a colorless, odorless, and tasteless noble gas. It is used in lighting, photography flashes, and laser applications.",
    },
    {
      symbol: "Rb",
      name: "Rubidium",
      atomicNumber: 37,
      family: "alkali metals",
      atomicMass: 85.468,
      period: 5,
      group: 1,
      density: 1.532,
      meltingPoint: 39.3,
      boilingPoint: 688,
      discoveryYear: 1861,
      discoveredBy: "Robert Bunsen and Gustav Kirchhoff",
      description:
        "Rubidium is a soft, silvery-white metallic element. It is highly reactive and is used in the production of vacuum tubes and photocells.",
    },
    {
      symbol: "Sr",
      name: "Strontium",
      atomicNumber: 38,
      family: "alkaline earth metals",
      atomicMass: 87.62,
      period: 5,
      group: 2,
      density: 2.64,
      meltingPoint: 777,
      boilingPoint: 1380,
      discoveryYear: 1790,
      discoveredBy: "Adair Crawford",
      description:
        "Strontium is a soft, silvery metal. It is used in fireworks to give a bright red color and in the production of ferrite magnets and glass for television cathode ray tubes.",
    },
    {
      symbol: "Y",
      name: "Yttrium",
      atomicNumber: 39,
      family: "transition metals",
      atomicMass: 88.906,
      period: 5,
      group: 3,
      density: 4.47,
      meltingPoint: 1523,
      boilingPoint: 3337,
      discoveryYear: 1794,
      discoveredBy: "Johan Gadolin",
      description:
        "Yttrium is a silvery-metallic transition metal. It is used in LEDs, phosphors, superconductors, and as a strengthening agent in metal alloys.",
    },
    {
      symbol: "Zr",
      name: "Zirconium",
      atomicNumber: 40,
      family: "transition metals",
      atomicMass: 91.224,
      period: 5,
      group: 4,
    },
    {
      symbol: "Zr",
      name: "Zirconium",
      atomicNumber: 40,
      family: "transition metals",
      atomicMass: 91.224,
      period: 5,
      group: 4,
      density: 6.52,
      meltingPoint: 2128,
      boilingPoint: 4682,
      discoveryYear: 1789,
      discoveredBy: "Martin Heinrich Klaproth",
      description:
        "Zirconium is a lustrous, grayish-white metal. It is highly resistant to corrosion and is commonly used in nuclear reactors, aerospace applications, and as an alloying agent in steel.",
    },
    {
      symbol: "Nb",
      name: "Niobium",
      atomicNumber: 41,
      family: "transition metals",
      atomicMass: 92.906,
      period: 5,
      group: 5,
      density: 8.57,
      meltingPoint: 2750,
      boilingPoint: 5017,
      discoveryYear: 1801,
      discoveredBy: "Charles Hatchett",
      description:
        "Niobium is a shiny, white, ductile metal. It is valued for its superconductive properties and is used in superalloys, jet engines, MRI machines, and particle accelerators.",
    },
    {
      symbol: "Mo",
      name: "Molybdenum",
      atomicNumber: 42,
      family: "transition metals",
      atomicMass: 95.95,
      period: 5,
      group: 6,
      density: 10.22,
      meltingPoint: 2896,
      boilingPoint: 4912,
      discoveryYear: 1778,
      discoveredBy: "Carl Wilhelm Scheele",
      description:
        "Molybdenum is a silvery-white metal with a high melting point. It is used primarily as an alloying agent in steel and other metals, as well as in lubricants, catalysts, and electronic applications.",
    },
    {
      symbol: "Tc",
      name: "Technetium",
      atomicNumber: 43,
      family: "transition metals",
      atomicMass: 98,
      period: 5,
      group: 7,
      density: 11.5,
      meltingPoint: 2430,
      boilingPoint: 4538,
      discoveryYear: 1937,
      discoveredBy: "Carlo Perrier, Emilio Segrè",
      description:
        "Technetium is a silvery-gray, radioactive metal. It is the first element to be artificially produced and does not occur naturally in the Earth's crust. It is used in nuclear medicine for diagnostic imaging.",
    },
    {
      symbol: "Ru",
      name: "Ruthenium",
      atomicNumber: 44,
      family: "transition metals",
      atomicMass: 101.07,
      period: 5,
      group: 8,
      density: 12.37,
      meltingPoint: 2607,
      boilingPoint: 4423,
      discoveryYear: 1844,
      discoveredBy: "Karl Ernst Claus",
      description:
        "Ruthenium is a rare, silvery-white metal. It is known for its hardness and resistance to corrosion. Ruthenium is used in electronics, jewelry, and as a catalyst in chemical reactions.",
    },
    {
      symbol: "Rh",
      name: "Rhodium",
      atomicNumber: 45,
      family: "transition metals",
      atomicMass: 102.91,
      period: 5,
      group: 9,
      density: 12.41,
      meltingPoint: 2237,
      boilingPoint: 3968,
      discoveryYear: 1803,
      discoveredBy: "William Hyde Wollaston",
      description:
        "Rhodium is a rare, silvery-white metal. It is highly reflective and resistant to corrosion. Rhodium is used in catalytic converters, jewelry, and as an alloying agent in platinum and palladium.",
    },
    {
      symbol: "Pd",
      name: "Palladium",
      atomicNumber: 46,
      family: "transition metals",
      atomicMass: 106.42,
      period: 5,
      group: 10,
      density: 12.02,
      meltingPoint: 1828.05,
      boilingPoint: 3236,
      discoveryYear: 1803,
      discoveredBy: "William Hyde Wollaston",
      description:
        "Palladium is a lustrous, silvery-white metal. It has excellent corrosion resistance and is used primarily in catalytic converters, electronics, and as a substitute for platinum in jewelry.",
    },
    {
      symbol: "Ag",
      name: "Silver",
      atomicNumber: 47,
      family: "transition metals",
      atomicMass: 107.87,
      period: 5,
      group: 11,
      density: 10.49,
      meltingPoint: 1234.93,
      boilingPoint: 2435,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Silver is a shiny, white metal known for its conductivity, malleability, and ductility. It is used in jewelry, currency, electronics, and as a catalyst in chemical reactions.",
    },
    {
      symbol: "Cd",
      name: "Cadmium",
      atomicNumber: 48,
      family: "transition metals",
      atomicMass: 112.41,
      period: 5,
      group: 12,
      density: 8.65,
      meltingPoint: 594.22,
      boilingPoint: 1040,
      discoveryYear: 1817,
      discoveredBy: "Friedrich Stromeyer",
      description:
        "Cadmium is a soft, bluish-white metal. It is highly toxic and is used primarily in batteries, coatings, pigments, and as a stabilizer in plastics.",
    },
    {
      symbol: "In",
      name: "Indium",
      atomicNumber: 49,
      family: "post-transition metals",
      atomicMass: 114.82,
      period: 5,
      group: 13,
      density: 7.31,
      meltingPoint: 429.75,
      boilingPoint: 2345,
      discoveryYear: 1863,
      discoveredBy: "Ferdinand Reich, Hieronymous Theodor Richter",
      description:
        "Indium is a soft, silvery-white metal. It is used in electronics, semiconductors, solar panels, and as an alloying agent in various metals.",
    },
    {
      symbol: "Sn",
      name: "Tin",
      atomicNumber: 50,
      family: "post-transition metals",
      atomicMass: 118.71,
      period: 5,
      group: 14,
      density: 7.29,
      meltingPoint: 505.08,
      boilingPoint: 2875,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Tin is a silvery-white metal known for its low toxicity and corrosion resistance. It is used in alloys, soldering, tin cans, and as a coating for other metals to prevent corrosion.",
    },
    {
      symbol: "Sb",
      name: "Antimony",
      atomicNumber: 51,
      family: "metalloids",
      atomicMass: 121.76,
      period: 5,
      group: 15,
      density: 6.68,
      meltingPoint: 903.78,
      boilingPoint: 1860,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Antimony is a silvery-white, brittle metalloid. It is used in flame retardants, batteries, semiconductors, and as an alloying agent in metals.",
    },
    {
      symbol: "Te",
      name: "Tellurium",
      atomicNumber: 52,
      family: "metalloids",
      atomicMass: 127.6,
      period: 5,
      group: 16,
      density: 6.24,
      meltingPoint: 722.66,
      boilingPoint: 1261,
      discoveryYear: 1782,
      discoveredBy: "Franz-Joseph Müller von Reichenstein",
      description:
        "Tellurium is a brittle, silvery-white metalloid. It is used in alloys, semiconductors, ceramics, and as a coloring agent in glass.",
    },
    {
      symbol: "I",
      name: "Iodine",
      atomicNumber: 53,
      family: "halogens",
      atomicMass: 126.904,
      period: 5,
      group: 17,
      density: 4.933,
      meltingPoint: 386.85,
      boilingPoint: 457.4,
      discoveryYear: 1811,
      discoveredBy: "Bernard Courtois",
      description:
        "Iodine is a shiny, purple-black nonmetallic element. It is essential for thyroid function in humans and is used in medicine, dyes, and photography.",
    },
    {
      symbol: "Xe",
      name: "Xenon",
      atomicNumber: 54,
      family: "noble gases",
      atomicMass: 131.293,
      period: 5,
      group: 18,
      density: 5.894,
      meltingPoint: 161.4,
      boilingPoint: 165.03,
      discoveryYear: 1898,
      discoveredBy: "Sir William Ramsay, Morris Travers",
      description:
        "Xenon is a colorless, odorless noble gas. It is used in lighting, medical imaging, lasers, and as an anesthetic in certain medical procedures.",
    },
    {
      symbol: "Cs",
      name: "Cesium",
      atomicNumber: 55,
      family: "alkali metals",
      atomicMass: 132.905,
      period: 6,
      group: 1,
      density: 1.93,
      meltingPoint: 301.7,
      boilingPoint: 944,
      discoveryYear: 1860,
      discoveredBy: "Robert Bunsen, Gustav Kirchhoff",
      description:
        "Cesium is a soft, silvery-gold alkali metal. It is one of the most electropositive and alkaline elements. Cesium is used in atomic clocks, photoelectric cells, and in drilling fluids for the oil industry.",
    },
    {
      symbol: "Ba",
      name: "Barium",
      atomicNumber: 56,
      family: "alkaline earth metals",
      atomicMass: 137.327,
      period: 6,
      group: 2,
      density: 3.62,
      meltingPoint: 1000,
      boilingPoint: 2170,
      discoveryYear: 1808,
      discoveredBy: "Sir Humphry Davy",
      description:
        "Barium is a soft, silvery alkaline earth metal. It is highly reactive with water and oxygen. Barium compounds are used in fireworks, rat poison, and in medical imaging of the gastrointestinal tract.",
    },
    {
      symbol: "La",
      name: "Lanthanum",
      atomicNumber: 57,
      family: "lanthanides",
      atomicMass: 138.905,
      period: 6,
      group: 3,
      density: 6.15,
      meltingPoint: 1193,
      boilingPoint: 3737,
      discoveryYear: 1839,
      discoveredBy: "Carl Gustaf Mosander",
      description:
        "Lanthanum is a silvery-white rare earth metal. It is ductile, malleable, and moderately reactive. Lanthanum is used in hybrid car batteries, camera lenses, and carbon arc lamps.",
    },
    {
      symbol: "Ce",
      name: "Cerium",
      atomicNumber: 58,
      family: "lanthanides",
      atomicMass: 140.116,
      period: 6,
      group: null,
      density: 6.77,
      meltingPoint: 1068,
      boilingPoint: 3716,
      discoveryYear: 1803,
      discoveredBy:
        "Jöns Jakob Berzelius, Wilhelm Hisinger, Martin Heinrich Klaproth",
      description:
        "Cerium is a soft, silvery-white metal. It is the most abundant of the rare earth elements and is used in catalysts, glass polishing, and as an alloying agent in magnesium alloys.",
    },
    {
      symbol: "Pr",
      name: "Praseodymium",
      atomicNumber: 59,
      family: "lanthanides",
      atomicMass: 140.907,
      period: 6,
      group: null,
      density: 6.77,
      meltingPoint: 1208,
      boilingPoint: 3793,
      discoveryYear: 1885,
      discoveredBy: "Carl Auer von Welsbach",
      description:
        "Praseodymium is a soft, silvery metal. It is used in rare earth magnets, laser glass, and as an alloying agent in metals.",
    },
    {
      symbol: "Nd",
      name: "Neodymium",
      atomicNumber: 60,
      family: "lanthanides",
      atomicMass: 144.242,
      period: 6,
      group: null,
      density: 7.01,
      meltingPoint: 1297,
      boilingPoint: 3347,
      discoveryYear: 1885,
      discoveredBy: "Carl Auer von Welsbach",
      description:
        "Neodymium is a soft, silvery metal. It is used in strong magnets (NdFeB magnets), lasers, and in glass to remove green coloration caused by iron impurities.",
    },
    {
      symbol: "Pm",
      name: "Promethium",
      atomicNumber: 61,
      family: "lanthanides",
      atomicMass: 145,
      period: 6,
      group: null,
      density: 7.26,
      meltingPoint: 1315,
      boilingPoint: 3273,
      discoveryYear: 1945,
      discoveredBy:
        "Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell",
      description:
        "Promethium is a radioactive rare earth metal. It is used in luminous paint, nuclear batteries, and as a source of beta particles for thickness gauges.",
    },
    {
      symbol: "Sm",
      name: "Samarium",
      atomicNumber: 62,
      family: "lanthanides",
      atomicMass: 150.36,
      period: 6,
      group: null,
      density: 7.52,
      meltingPoint: 1345,
      boilingPoint: 2173,
      discoveryYear: 1853,
      discoveredBy: "Lecoq de Boisbaudran",
      description:
        "Samarium is a silvery metal. It is used in magnets, infrared absorbing glass, and as a neutron absorber in nuclear reactors.",
    },
    {
      symbol: "Eu",
      name: "Europium",
      atomicNumber: 63,
      family: "lanthanides",
      atomicMass: 151.964,
      period: 6,
      group: null,
      density: 5.24,
      meltingPoint: 1095,
      boilingPoint: 1802,
      discoveryYear: 1901,
      discoveredBy: "Eugène-Anatole Demarçay",
      description:
        "Europium is a silvery-white metal. It is used in phosphorescent powder for cathode ray tubes, as a dopant in lasers, and in nuclear reactor control rods",
    },
    {
      symbol: "Gd",
      name: "Gadolinium",
      atomicNumber: 64,
      family: "lanthanides",
      atomicMass: 157.25,
      period: 6,
      group: null,
      density: 7.9,
      meltingPoint: 1312,
      boilingPoint: 3000,
      discoveryYear: 1880,
      discoveredBy: "Jean Charles Galissard de Marignac",
      description:
        "Gadolinium is a silvery-white metal. It is used in magnetic resonance imaging (MRI) contrast agents, neutron capture therapy for cancer, and in computer memory.",
    },
    {
      symbol: "Tb",
      name: "Terbium",
      atomicNumber: 65,
      family: "lanthanides",
      atomicMass: 158.925,
      period: 6,
      group: null,
      density: 8.23,
      meltingPoint: 1356,
      boilingPoint: 3230,
      discoveryYear: 1843,
      discoveredBy: "Carl Gustaf Mosander",
      description:
        "Terbium is a silvery-gray rare earth metal. It is used in green phosphors for fluorescent lamps and as an additive in permanent magnets.",
    },
    {
      symbol: "Dy",
      name: "Dysprosium",
      atomicNumber: 66,
      family: "lanthanides",
      atomicMass: 162.5,
      period: 6,
      group: null,
      density: 8.54,
      meltingPoint: 1412,
      boilingPoint: 2567,
      discoveryYear: 1886,
      discoveredBy: "Paul Émile Lecoq de Boisbaudran",
      description:
        "Dysprosium is a silvery-white rare earth metal. It is used in control rods for nuclear reactors, data storage in hard disk drives, and in lasers.",
    },
    {
      symbol: "Ho",
      name: "Holmium",
      atomicNumber: 67,
      family: "lanthanides",
      atomicMass: 164.93,
      period: 6,
      group: null,
      density: 8.79,
      meltingPoint: 1470,
      boilingPoint: 2720,
      discoveryYear: 1878,
      discoveredBy: "Marc Delafontaine, Jacques-Louis Soret",
      description:
        "Holmium is a soft, silvery-white metal. It is used in high-strength magnets (HoFeB magnets), lasers, and as a component in some alloys.",
    },
    {
      symbol: "Er",
      name: "Erbium",
      atomicNumber: 68,
      family: "lanthanides",
      atomicMass: 167.259,
      period: 6,
      group: null,
      density: 9.07,
      meltingPoint: 1529,
      boilingPoint: 2868,
      discoveryYear: 1843,
      discoveredBy: "Carl Gustaf Mosander",
      description:
        "Erbium is a silvery-white metal. It is used in fiber optic communications, lasers, and as a dopant in some types of glass to amplify signals in optical fibers.",
    },
    {
      symbol: "Tm",
      name: "Thulium",
      atomicNumber: 69,
      family: "lanthanides",
      atomicMass: 168.934,
      period: 6,
      group: null,
      density: 9.32,
      meltingPoint: 1545,
      boilingPoint: 1950,
      discoveryYear: 1879,
      discoveredBy: "Per Teodor Cleve",
      description:
        "Thulium is a silvery-gray metal. It is used in portable X-ray devices, lasers, and as a radiation source for cancer treatment.",
    },
    {
      symbol: "Yb",
      name: "Ytterbium",
      atomicNumber: 70,
      family: "lanthanides",
      atomicMass: 173.045,
      period: 6,
      group: null,
      density: 6.9,
      meltingPoint: 824,
      boilingPoint: 1196,
      discoveryYear: 1878,
      discoveredBy: "Jean Charles Galissard de Marignac",
      description:
        "Ytterbium is a soft, malleable silver-metallic element. It is used in lasers, nuclear medicine, and as a dopant in stainless steel to improve its properties.",
    },
    {
      symbol: "Lu",
      name: "Lutetium",
      atomicNumber: 71,
      family: "lanthanides",
      atomicMass: 174.967,
      period: 6,
      group: null,
      density: 9.84,
      meltingPoint: 1656,
      boilingPoint: 3315,
      discoveryYear: 1907,
      discoveredBy: "Georges Urbain, Carl Auer von Welsbach",
      description:
        "Lutetium is a silvery-white rare earth metal. It is used in catalysts, medical imaging, and in research as a standard for the measurement of radioactivity.",
    },
    {
      symbol: "Hf",
      name: "Hafnium",
      atomicNumber: 72,
      family: "transition metals",
      atomicMass: 178.49,
      period: 6,
      group: 4,
      density: 13.31,
      meltingPoint: 2506,
      boilingPoint: 4876,
      discoveryYear: 1923,
      discoveredBy: "Dirk Coster, George de Hevesy",
      description:
        "Hafnium is a lustrous, silvery-gray metal. It is used in nuclear reactors, gas turbines, and in the aerospace industry due to its high melting point and corrosion resistance.",
    },
    {
      symbol: "Ta",
      name: "Tantalum",
      atomicNumber: 73,
      family: "transition metals",
      atomicMass: 180.948,
      period: 6,
      group: 5,
      density: 16.69,
      meltingPoint: 3290,
      boilingPoint: 5731,
      discoveryYear: 1802,
      discoveredBy: "Anders Gustaf Ekeberg",
      description:
        "Tantalum is a rare, blue-gray metal. It is highly corrosion-resistant and is used in capacitors, surgical implants, chemical equipment, and in alloys for jet engines.",
    },
    {
      symbol: "W",
      name: "Tungsten",
      atomicNumber: 74,
      family: "transition metals",
      atomicMass: 183.84,
      period: 6,
      group: 6,
      density: 19.25,
      meltingPoint: 3695,
      boilingPoint: 5828,
      discoveryYear: 1781,
      discoveredBy: "Juan José Elhuyar, Fausto Elhuyar",
      description:
        "Tungsten is a hard, gray-white metal. It has the highest melting point of all metals and is used in light bulb filaments, X-ray tubes, and as an alloying agent in steel.",
    },
    {
      symbol: "Re",
      name: "Rhenium",
      atomicNumber: 75,
      family: "transition metals",
      atomicMass: 186.207,
      period: 6,
      group: 7,
      density: 21.02,
      meltingPoint: 3459,
      boilingPoint: 5869,
      discoveryYear: 1925,
      discoveredBy: "Walter Noddack, Ida Noddack, Otto Berg",
      description:
        "Rhenium is a silvery-white, rare transition metal. It is one of the densest and highest-melting elements. Rhenium is used in superalloys for jet engines",
    },
    {
      symbol: "Os",
      name: "Osmium",
      atomicNumber: 76,
      family: "transition metals",
      atomicMass: 190.23,
      period: 6,
      group: 8,
      density: 22.59,
      meltingPoint: 3306,
      boilingPoint: 5285,
      discoveryYear: 1803,
      discoveredBy: "Smithson Tennant",
      description:
        "Osmium is a hard, brittle, blue-gray transition metal. It is the densest naturally occurring element and is used in alloys, electrical contacts, and in fountain pen tips.",
    },
    {
      symbol: "Ir",
      name: "Iridium",
      atomicNumber: 77,
      family: "transition metals",
      atomicMass: 192.217,
      period: 6,
      group: 9,
      density: 22.56,
      meltingPoint: 2719,
      boilingPoint: 4701,
      discoveryYear: 1803,
      discoveredBy: "Smithson Tennant",
      description:
        "Iridium is a very hard, brittle, silvery-white transition metal. It is the most corrosion-resistant metal and is used in spark plugs, crucibles for high-temperature applications, and in some jewelry.",
    },
    {
      symbol: "Pt",
      name: "Platinum",
      atomicNumber: 78,
      family: "transition metals",
      atomicMass: 195.084,
      period: 6,
      group: 10,
      density: 21.45,
      meltingPoint: 2041.4,
      boilingPoint: 4098,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Platinum is a dense, malleable, silvery-white transition metal. It is one of the rarest elements in the Earth's crust and is used in jewelry, catalytic converters, and as a standard for measuring weights and measures.",
    },
    {
      symbol: "Au",
      name: "Gold",
      atomicNumber: 79,
      family: "transition metals",
      atomicMass: 196.967,
      period: 6,
      group: 11,
      density: 19.32,
      meltingPoint: 1337.33,
      boilingPoint: 3080,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Gold is a dense, soft, yellow transition metal. It is highly ductile and malleable, making it ideal for jewelry, currency, and as a conductor of electricity.",
    },
    {
      symbol: "Hg",
      name: "Mercury",
      atomicNumber: 80,
      family: "transition metals",
      atomicMass: 200.592,
      period: 6,
      group: 12,
      density: 13.5336,
      meltingPoint: 234.321,
      boilingPoint: 629.88,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Mercury is a dense, silvery-white transition metal. It is the only metal that is liquid at standard conditions for temperature and pressure. Mercury is used in thermometers, barometers, and in dental amalgams.",
    },
    {
      symbol: "Tl",
      name: "Thallium",
      atomicNumber: 81,
      family: "post-transition metals",
      atomicMass: 204.38,
      period: 6,
      group: 13,
      density: 11.85,
      meltingPoint: 577,
      boilingPoint: 1746,
      discoveryYear: 1861,
      discoveredBy: "William Crookes",
      description:
        "Thallium is a soft, bluish-gray post-transition metal. It is highly toxic and was historically used as a rat poison and in some medical treatments. Thallium is also used in photocells and in infrared detectors.",
    },
    {
      symbol: "Pb",
      name: "Lead",
      atomicNumber: 82,
      family: "post-transition metals",
      atomicMass: 207.2,
      period: 6,
      group: 14,
      density: 11.34,
      meltingPoint: 600.61,
      boilingPoint: 2022,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Lead is a heavy, soft, bluish-gray post-transition metal. It is highly malleable and corrosion-resistant. Lead is used in batteries, radiation shielding, and in some alloys.",
    },
    {
      symbol: "Bi",
      name: "Bismuth",
      atomicNumber: 83,
      family: "post-transition metals",
      atomicMass: 208.98,
      period: 6,
      group: 15,
      density: 9.78,
      meltingPoint: 544.7,
      boilingPoint: 1837,
      discoveryYear: "Ancient",
      discoveredBy: "Unknown",
      description:
        "Bismuth is a brittle, pinkish-white post-transition metal. It is the most naturally diamagnetic element and is used in cosmetics, pharmaceuticals, and as a replacement for lead in some applications.",
    },
    {
      symbol: "Po",
      name: "Polonium",
      atomicNumber: 84,
      family: "post-transition metals",
      atomicMass: 209,
      period: 6,
      group: 16,
      density: 9.196,
      meltingPoint: 527,
      boilingPoint: 1235,
      discoveryYear: 1898,
      discoveredBy: "Marie Curie, Pierre Curie",
      description:
        "Polonium is a rare and highly radioactive metal. It is used in static eliminators and as a heat source in space probes.",
    },
    {
      symbol: "At",
      name: "Astatine",
      atomicNumber: 85,
      family: "halogens",
      atomicMass: 210,
      period: 6,
      group: 17,
      density: null,
      meltingPoint: 575,
      boilingPoint: 610,
      discoveryYear: 1940,
      discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
      description:
        "Astatine is a very rare and highly radioactive halogen. It is sometimes referred to as the rarest naturally occurring element.",
    },
    {
      symbol: "Rn",
      name: "Radon",
      atomicNumber: 86,
      family: "noble gases",
      atomicMass: 222,
      period: 6,
      group: 18,
      density: 9.73,
      meltingPoint: 202,
      boilingPoint: 211.5,
      discoveryYear: 1900,
      discoveredBy: "Friedrich Ernst Dorn",
      description:
        "Radon is a colorless, odorless, radioactive noble gas. It is produced by the radioactive decay of radium and is used in cancer treatment and as a tracer in geologic research.",
    },
    {
      symbol: "Fr",
      name: "Francium",
      atomicNumber: 87,
      family: "alkali metals",
      atomicMass: 223,
      period: 7,
      group: 1,
      density: null,
      meltingPoint: 300,
      boilingPoint: 950,
      discoveryYear: 1939,
      discoveredBy: "Marguerite Perey",
      description:
        "Francium is an extremely rare alkali metal. It is highly radioactive and the least stable of the first 101 elements. Francium has no commercial applications due to its rarity and radioactivity.",
    },
    {
      symbol: "Ra",
      name: "Radium",
      atomicNumber: 88,
      family: "alkaline earth metals",
      atomicMass: 226,
      period: 7,
      group: 2,
      density: 5.5,
      meltingPoint: 973,
      boilingPoint: 2010,
      discoveryYear: 1898,
      discoveredBy: "Marie Curie, Pierre Curie",
      description:
        "Radium is a highly radioactive alkaline earth metal. It glows faintly in the dark due to its radioactivity. Radium was formerly used in luminous paints and in cancer treatment, though its use is now limited due to its health risks.",
    },
    {
      symbol: "Ac",
      name: "Actinium",
      atomicNumber: 89,
      family: "actinides",
      atomicMass: 227,
      period: 7,
      group: 3,
      density: 10.07,
      meltingPoint: 1323,
      boilingPoint: 3471,
      discoveryYear: 1899,
      discoveredBy: "Friedrich Oskar Giesel",
      description:
        "Actinium is a silvery-white, radioactive metal. It glows faintly in the dark due to its radioactivity. Actinium is used in neutron sources and as a radiation therapy for cancer treatment.",
    },
    {
      symbol: "Th",
      name: "Thorium",
      atomicNumber: 90,
      family: "actinides",
      atomicMass: 232.0377,
      period: 7,
      group: null,
      density: 11.72,
      meltingPoint: 2023,
      boilingPoint: 5061,
      discoveryYear: 1828,
      discoveredBy: "Jöns Jakob Berzelius",
      description:
        "Thorium is a silvery-white, radioactive metal. It is used in nuclear reactors as a nuclear fuel, in magnesium alloys, and in some high-temperature applications.",
    },
    {
      symbol: "Pa",
      name: "Protactinium",
      atomicNumber: 91,
      family: "actinides",
      atomicMass: 231.03588,
      period: 7,
      group: null,
      density: 15.37,
      meltingPoint: 1841,
      boilingPoint: 4300,
      discoveryYear: 1913,
      discoveredBy: "Kasimir Fajans, Oswald Helmuth Göhring",
      description:
        "Protactinium is a dense, silvery-gray, radioactive metal. It is used in research as a neutron source and in nuclear applications.",
    },
    {
      symbol: "U",
      name: "Uranium",
      atomicNumber: 92,
      family: "actinides",
      atomicMass: 238.02891,
      period: 7,
      group: null,
      density: 19.1,
      meltingPoint: 1405.3,
      boilingPoint: 4404,
      discoveryYear: 1789,
      discoveredBy: "Martin Heinrich Klaproth",
      description:
        "Uranium is a dense, silvery-white, radioactive metal. It is primarily used as a nuclear fuel in nuclear power plants and in nuclear weapons. Uranium is also used in some medical applications.",
    },
    {
      symbol: "Np",
      name: "Neptunium",
      atomicNumber: 93,
      family: "actinides",
      atomicMass: 237,
      period: 7,
      group: null,
      density: 20.45,
      meltingPoint: 917,
      boilingPoint: 4273,
      discoveryYear: 1940,
      discoveredBy: "Edwin McMillan, Philip Abelson",
      description:
        "Neptunium is a silvery radioactive metal. It is used in research and in some nuclear reactors as a neutron source.",
    },
    {
      symbol: "Pu",
      name: "Plutonium",
      atomicNumber: 94,
      family: "actinides",
      atomicMass: 244,
      period: 7,
      group: null,
      density: 19.84,
      meltingPoint: 912.5,
      boilingPoint: 3501,
      discoveryYear: 1940,
      discoveredBy:
        "Glenn T. Seaborg, Arthur Wahl, Joseph W. Kennedy, Edwin McMillan",
      description:
        "Plutonium is a silvery radioactive metal. It is primarily used in nuclear weapons and as a nuclear fuel in some reactors. Plutonium-238 is used in radioisotope thermoelectric generators for spacecraft and in some pacemakers.",
    },
    {
      symbol: "Am",
      name: "Americium",
      atomicNumber: 95,
      family: "actinides",
      atomicMass: 243,
      period: 7,
      group: null,
      density: 13.67,
      meltingPoint: 1449,
      boilingPoint: 2880,
      discoveryYear: 1944,
      discoveredBy:
        "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
      description:
        "Americium is a silvery-white radioactive metal. It is used in smoke detectors and in some medical and industrial applications as a source of gamma rays.",
    },
    {
      symbol: "Cm",
      name: "Curium",
      atomicNumber: 96,
      family: "actinides",
      atomicMass: 247,
      period: 7,
      group: null,
      density: 13.51,
      meltingPoint: 1340,
      boilingPoint: 3110,
      discoveryYear: 1944,
      discoveredBy: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
      description:
        "Curium is a silvery radioactive metal. It is primarily used in research and in some types of nuclear reactors as a neutron source.",
    },
    {
      symbol: "Bk",
      name: "Berkelium",
      atomicNumber: 97,
      family: "actinides",
      atomicMass: 247,
      period: 7,
      group: null,
      density: 14.78,
      meltingPoint: 986,
      boilingPoint: null,
      discoveryYear: 1949,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Berkelium is a silvery-white radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Cf",
      name: "Californium",
      atomicNumber: 98,
      family: "actinides",
      atomicMass: 251,
      period: 7,
      group: null,
      density: 15.1,
      meltingPoint: 1173,
      boilingPoint: null,
      discoveryYear: 1950,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Californium is a radioactive metal. It is primarily used in research and has some applications as a neutron source.",
    },
    {
      symbol: "Es",
      name: "Einsteinium",
      atomicNumber: 99,
      family: "actinides",
      atomicMass: 252,
      period: 7,
      group: null,
      density: 8.84,
      meltingPoint: 1133,
      boilingPoint: null,
      discoveryYear: 1952,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Einsteinium is a synthetic element and radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Fm",
      name: "Fermium",
      atomicNumber: 100,
      family: "actinides",
      atomicMass: 257,
      period: 7,
      group: null,
      density: null,
      meltingPoint: 1800,
      boilingPoint: null,
      discoveryYear: 1952,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Fermium is a synthetic radioactive element. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Md",
      name: "Mendelevium",
      atomicNumber: 101,
      family: "actinides",
      atomicMass: 258,
      period: 7,
      group: null,
      density: null,
      meltingPoint: 1100,
      boilingPoint: null,
      discoveryYear: 1955,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Mendelevium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "No",
      name: "Nobelium",
      atomicNumber: 102,
      family: "actinides",
      atomicMass: 259,
      period: 7,
      group: null,
      density: null,
      meltingPoint: 1100,
      boilingPoint: null,
      discoveryYear: 1958,
      discoveredBy: "Joint Institute for Nuclear Research",
      description:
        "Nobelium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Lr",
      name: "Lawrencium",
      atomicNumber: 103,
      family: "actinides",
      atomicMass: 266,
      period: 7,
      group: 3,
      density: null,
      meltingPoint: 1900,
      boilingPoint: null,
      discoveryYear: 1961,
      discoveredBy: "Lawrence Berkeley National Laboratory",
      description:
        "Lawrencium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Rf",
      name: "Rutherfordium",
      atomicNumber: 104,
      family: "transition metals",
      atomicMass: 267,
      period: 7,
      group: 4,
      density: null,
      meltingPoint: 2400,
      boilingPoint: null,
      discoveryYear: 1969,
      discoveredBy:
        "Joint Institute for Nuclear Research, Lawrence Berkeley National Laboratory",
      description:
        "Rutherfordium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Db",
      name: "Dubnium",
      atomicNumber: 105,
      family: "transition metals",
      atomicMass: 268,
      period: 7,
      group: 5,
      density: null,
      meltingPoint: 2700,
      boilingPoint: null,
      discoveryYear: 1967,
      discoveredBy: "Joint Institute for Nuclear Research",
      description:
        "Dubnium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Sg",
      name: "Seaborgium",
      atomicNumber: 106,
      family: "transition metals",
      atomicMass: 269,
      period: 7,
      group: 6,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1974,
      discoveredBy:
        "Lawrence Berkeley National Laboratory, Joint Institute for Nuclear Research",
      description:
        "Seaborgium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Bh",
      name: "Bohrium",
      atomicNumber: 107,
      family: "transition metals",
      atomicMass: 270,
      period: 7,
      group: 7,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1981,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Bohrium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Hs",
      name: "Hassium",
      atomicNumber: 108,
      family: "transition metals",
      atomicMass: 269,
      period: 7,
      group: 8,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1984,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Hassium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Mt",
      name: "Meitnerium",
      atomicNumber: 109,
      family: "transition metals",
      atomicMass: 278,
      period: 7,
      group: 9,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1982,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Meitnerium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Ds",
      name: "Darmstadtium",
      atomicNumber: 110,
      family: "transition metals",
      atomicMass: 281,
      period: 7,
      group: 10,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1994,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Darmstadtium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Rg",
      name: "Roentgenium",
      atomicNumber: 111,
      family: "transition metals",
      atomicMass: 282,
      period: 7,
      group: 11,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1994,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Roentgenium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Cn",
      name: "Copernicium",
      atomicNumber: 112,
      family: "transition metals",
      atomicMass: 285,
      period: 7,
      group: 12,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1996,
      discoveredBy: "Gesellschaft für Schwerionenforschung",
      description:
        "Copernicium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Nh",
      name: "Nihonium",
      atomicNumber: 113,
      family: "post-transition metals",
      atomicMass: 286,
      period: 7,
      group: 13,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 2004,
      discoveredBy:
        "RIKEN, Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory",
      description:
        "Nihonium is a synthetic radioactive metal. It is one of the newest elements to be discovered and is primarily used in research.",
    },
    {
      symbol: "Fl",
      name: "Flerovium",
      atomicNumber: 114,
      family: "post-transition metals",
      atomicMass: 289,
      period: 7,
      group: 14,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 1998,
      discoveredBy: "Joint Institute for Nuclear Research",
      description:
        "Flerovium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Mc",
      name: "Moscovium",
      atomicNumber: 115,
      family: "post-transition metals",
      atomicMass: 290,
      period: 7,
      group: 15,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 2003,
      discoveredBy:
        "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory, Oak Ridge National Laboratory",
      description:
        "Moscovium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Lv",
      name: "Livermorium",
      atomicNumber: 116,
      family: "post-transition metals",
      atomicMass: 293,
      period: 7,
      group: 16,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 2000,
      discoveredBy:
        "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory",
      description:
        "Livermorium is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Ts",
      name: "Tennessine",
      atomicNumber: 117,
      family: "post-transition metals",
      atomicMass: 294,
      period: 7,
      group: 17,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 2010,
      discoveredBy:
        "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory, Oak Ridge National Laboratory, Vanderbilt University",
      description:
        "Tennessine is a synthetic radioactive metal. It is primarily used in research and has no significant commercial applications.",
    },
    {
      symbol: "Og",
      name: "Oganesson",
      atomicNumber: 118,
      family: "noble gases",
      atomicMass: 294,
      period: 7,
      group: 18,
      density: null,
      meltingPoint: null,
      boilingPoint: null,
      discoveryYear: 2002,
      discoveredBy:
        "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory, Oak Ridge National Laboratory",
      description:
        "Oganesson is a synthetic radioactive noble gas. It is primarily used in research and has no significant commercial applications.",
    },
  ];

const periodicTable = document.querySelector(".periodic-table");
const lanthanidesTable = document.querySelector(".lanthanides-table");
const actinidesTable = document.querySelector(".actinides-table");
const modal = document.getElementById("elementModal");
const modalContent = document.getElementById("modalContent");
const closeModal = document.querySelector(".close");

// Function to generate elements in the periodic table
function generatePeriodicTable() {
  // Array to hold 7 periods, each with 18 slots
  const tableGrid = Array.from({ length: 7 }, () => Array.from({ length: 18 }));

  elements.forEach((element) => {
    const { symbol, name, atomicNumber, group, period, family, description } =
      element;

    // Create element div
    const elementDiv = document.createElement("div");
    elementDiv.classList.add(
      "element",
      family.toLowerCase().replace(/ /g, "-")
    );

    // Add symbol and number
    const symbolSpan = document.createElement("span");
    symbolSpan.classList.add("symbol");
    symbolSpan.textContent = symbol;
    elementDiv.appendChild(symbolSpan);

    const numberSpan = document.createElement("span");
    numberSpan.classList.add("number");
    numberSpan.textContent = atomicNumber;
    elementDiv.appendChild(numberSpan);

    // Add name of the element
    const nameSpan = document.createElement("span");
    nameSpan.classList.add("element-name");
    nameSpan.textContent = name;
    elementDiv.appendChild(nameSpan);

    // Add click event to show modal with details
    elementDiv.addEventListener("click", () => {
      modalContent.innerHTML = `
                    <h2>${name} (${symbol})</h2>
                    <p><strong>Atomic Number:</strong> ${atomicNumber}</p>
                    <p><strong>Family:</strong> ${family}</p>
                    <p><strong>Group:</strong> ${group ?? "N/A"}</p>
                    <p><strong>Period:</strong> ${period}</p>
                    <p><strong>Description:</strong> ${description}</p>
                    <p><strong>Discovered By:</strong> ${
                      element.discoveredBy
                    }, ${element.discoveryYear}</p>
                `;
      modal.style.display = "block";
    });

    if (group === null) {
      if (atomicNumber >= 58 && atomicNumber <= 71) {
        lanthanidesTable.appendChild(elementDiv);
      } else if (atomicNumber >= 90 && atomicNumber <= 103) {
        actinidesTable.appendChild(elementDiv);
      }
    } else {
      // Calculate position in the grid
      const row = period - 1; // periods are 1-indexed
      const col = group - 1; // groups are 1-indexed

      // Add element to the grid position
      tableGrid[row][col] = elementDiv;
    }
  });

  // Flatten the tableGrid and append elements to the DOM
  tableGrid.flat().forEach((elementDiv) => {
    if (elementDiv) {
      periodicTable.appendChild(elementDiv);
    } else {
      // Create placeholder for empty slots (for future expansion)
      const emptySlot = document.createElement("div");
      emptySlot.classList.add("empty");
      periodicTable.appendChild(emptySlot);
    }
  });
}

// Close modal function
closeModal.addEventListener("click", () => {
  modal.style.display = "none";
});

// Generate the periodic table when DOM is loaded
document.addEventListener("DOMContentLoaded", generatePeriodicTable);


  generatePeriodicTable();
});
